### ISSUE TITLE
Loading from `esm.sh`

### ISSUE THREAD

**Issue by tantaman** [tomayac/sqlite-wasm#10]
Trying to load from `esm.sh` and the package looks for the WASM @ `https://esm.sh/@sqlite.org/sqlite-wasm@3.41.2/sqlite3.wasm` where as it is really located at https://esm.sh/@sqlite.org/sqlite-wasm@3.41.2/sqlite-wasm/jswasm/sqlite3.wasm

Could you move the wasm to the root directory so it resolves correctly or fix the wasm resolution code? Given this is a direct copy from the sqlite repo with no code changes, the former is probably the only workable solution.

**Comment by tomayac** [comment]
I get an issue about `BigInt` not being supported or a timeout issue on esm.sh. 

Could you try an alternative CDN for testing, such as https://cdn.jsdelivr.net/npm/@sqlite.org/sqlite-wasm or https://unpkg.com/@sqlite.org/sqlite-wasm@3.41.2-build13/index.mjs.

**Comment by tantaman** [comment]
Weird. I deployed my own forked version that copies the wasm into the root dir.

I'm able to use that without issue here: https://vlcn.io/articles/recursive-ordering-in-sqlite

If you scroll down there's a runnable code box (kind of like a python notebook) which is importing and running sqlite.

![Screenshot 2023-05-18 at 12 24 16 PM](https://github.com/tomayac/sqlite-wasm/assets/1009003/ce23f620-6157-4d00-930f-5c54e72ba786)

---

Trying your suggestion and modifying that import --

jsdeliver fails but unpkg works 🤔 The wonderful world of javascript...

I'll update to just use unpkg.

**Comment by ije** [comment]
@tantaman i think this a bug of esm.sh of the bunder breaks the wasm file from `new URL('sqlite3.wasm', import.meta.url).href`, i will fix

**Comment by ije** [comment]
<img width="1123" alt="Screenshot 2023-05-20 at 23 32 15" src="https://github.com/tomayac/sqlite-wasm/assets/2883484/d395a348-92ad-4539-83aa-349a54dac645">

@tantaman would like to try again? thanks

**Comment by tantaman** [comment]
@ije  - that works, thanks.
