### ISSUE TITLE
is sqlite3-opfs-async-proxy.js some can turn off?

### ISSUE THREAD

**Issue by vegarringdal** [tomayac/sqlite-wasm#11]
Been playing around with this module last days and been having so much fun 😄. 
Thanks for making this module 🥇 👍 

Noticed I get these per worker I use it in. (see image)
Is this needed for OPFS when I use it in a worker?
I though sync file handle could be used in workers.
But I might be wrong/missing something, so much I dont know 😂 

![image](https://github.com/tomayac/sqlite-wasm/assets/2901416/40951463-4ce3-4fa9-a116-1f6741df4ed2)

**Comment by sgbeal** [comment]
Those are either coming from your browser or perhaps your local dev tools inject something to add that info. Those do not come from this project's code.

**Comment by vegarringdal** [comment]
Though it was something module did, since I saw this file. (see image)
I will have a new look, maybe Ive done something weird.
Thanks for the quick response 🥇 

![image](https://github.com/tomayac/sqlite-wasm/assets/2901416/0127ca6c-4c26-448b-8042-7335925829d9)

**Comment by sgbeal** [comment]
i may be misunderstanding what you were asking: i thought the question was why the output is produced, but a re-read clarifies that you're asking if that file is needed. That file indeed comes from this package but the output you're seeing regarding I/O does not. That file will be loaded if the library determines that OPFS is available. If it does not see the required OPFS APIs then it will not load that file.

**Comment by vegarringdal** [comment]
Yes, see my image was kinda bad too. 😂  Added a better one now.
Thought I might be using the package wrong at first. Since it looked like a helper worker for using sqllite on main thread.

![image](https://github.com/tomayac/sqlite-wasm/assets/2901416/8e1f3c96-277d-4a83-b0e5-934ff005c369)

**Comment by sgbeal** [comment]
Note that the sqlite library code _can_ run in the main thread, but OPFS is not available there. In the main thread it can use transient storage (in-memory in a pseudo-filesystem provided by Emscripten) or it can use localStorage and/or sessionStorage to store _small_ databases persistently. See <https://sqlite.org/wasm/doc/trunk/persistence.md> for details.

**Comment by vegarringdal** [comment]
Only reason why I started on this was to use OPFS.
Need go away from keeping all data in memory :-)
Experimenting with many db spread over many workers to speed up query over X million rows.
Just need to find out how many workers I can have before I break the browser breaks 😂
