### ISSUE TITLE
Does not work in node environment (upstream v3.42)

### ISSUE THREAD

**Issue by chuanqisun** [tomayac/sqlite-wasm#16]
Hi, I'm trying to use sqlite-wasm in both browser and node environment. The node environment is used for unit test. I don't expect OPFS to work so I switched to in-memory DB instead. When I run the sample code, it looks like the library is still expecting browser environment and throws an error:

```
Loading and initializing SQLite3 module...
Process exited with code 1
Exception loading sqlite3 module: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11) {cause: Error: not implemented... yet...
    at makeNe…or (node:internal/deps/undici/undici:6802:35)…, stack: 'TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)', message: 'fetch failed'}
Uncaught TypeError TypeError: fetch failed
    at fetch (internal/deps/undici/undici:11457:11)

```

Here is the screenshot of the setup. My node version is `20.0.0`

![image](https://github.com/tomayac/sqlite-wasm/assets/1895289/cfe6a66c-8e82-4900-b6a0-bc14648f28e3)

I noticed that 3.42 ships with a `sqlite-node.mjs` file. So I hard coded the import path to it:
![image](https://github.com/tomayac/sqlite-wasm/assets/1895289/e127bebb-e1d5-4409-ac5f-83a3725698bf)

And got a `self` error seemingly related to #3 
```
sqlite3 bootstrap initializer threw: ReferenceError: self is not defined
    at StructBinderFactory (/workspaces/tinykb/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:7859:20)
    at /workspaces/tinykb/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:9321:43
    at /workspaces/tinykb/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:6686:13
    at Array.forEach (<anonymous>)
    at sqlite3ApiBootstrap (/workspaces/tinykb/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:6685:44)
    at /workspaces/tinykb/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:13243:32
    at callRuntimeCallbacks (/workspaces/tinykb/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:681:26)
    at postRun (/workspaces/tinykb/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:459:7)
    at doRun (/workspaces/tinykb/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:5642:9)
    at run (file:///workspaces/tinykb/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:5654:9) {stack: 'ReferenceError: self is not defined
    at St…m/sqlite-wasm/jswasm/sqlite3-node.mjs:5654:9)', message: 'self is not defined'}
```

I understand if there is no official support for node.js runtime due to lack of dev resource. I'd still like to propose such a feature as it allows test driven development.  In the js ecosystem, most unit test setups require node.js based runtime. Also, wasm is supposed to be the universal binary format that is agnostic of browser vs. node.js (or even deno), so it would be amazing for sqlite to work anywhere wasm runs.

**Comment by sgbeal** [comment]
i'll fix the dangling "self" references tomorrow (it's late here). We don't officially/directly support node for the very simple reason that nobody in the sqlite project uses node in any capacity, and attempting to support a platform you don't actually use is a lost cause.

**Comment by sgbeal** [comment]
The remaining "self" references have been replaced with "globalThis" and will show up in the next 2.42.x and 2.43 releases.

About the fetch() call: that's coming from Emscripten-generated code, which we have little influence over. However, the sqlite3-node.mjs build variant has that call blocked off when it's run in node:

```js
  if (!binary &&
      typeof WebAssembly.instantiateStreaming == 'function' &&
      !isDataURI(binaryFile) &&
      // Avoid instantiateStreaming() on Node.js environment for now, as while
      // Node.js v18.1.0 implements it, it does not have a full fetch()
      // implementation yet.
      //
      // Reference:
      //   https://github.com/emscripten-core/emscripten/pull/16917
      !ENVIRONMENT_IS_NODE &&
      typeof fetch == 'function') {
    return fetch(binaryFile, { credentials: 'same-origin' }).then((response) => {
...
```

**Comment by sgbeal** [comment]
(Oooops - just deleted the closure comment because github showed it as duplicately posted when it wasn't. Rewriting...)

The "self" references have been replaced with "globalThis" upstream. That change will appear in the next 2.42.x and 2.43 releases.

As to fetch(), that comes from Emscripten-generated code. The sqlite3-node.mjs build variant blocks out that call when run from node:

```js
  if (!binary &&
      typeof WebAssembly.instantiateStreaming == 'function' &&
      !isDataURI(binaryFile) &&
      // Avoid instantiateStreaming() on Node.js environment for now, as while
      // Node.js v18.1.0 implements it, it does not have a full fetch()
      // implementation yet.
      //
      // Reference:
      //   https://github.com/emscripten-core/emscripten/pull/16917
      !ENVIRONMENT_IS_NODE &&
      typeof fetch == 'function') {
    return fetch(binaryFile, { credentials: 'same-origin' }).then((response) => {
```

**Comment by irisjae** [comment]
I'm still seeing the use of self and the associated error on [3.45.3-build1](https://github.com/sqlite/sqlite-wasm/blob/c165098b9b1a97764810e7dd7fb059e313aeb727/index.mjs); what's the plan for merging this?

**Comment by irisjae** [comment]
> (Oooops - just deleted the closure comment because github showed it as duplicately posted when it wasn't. Rewriting...)
> 
> The "self" references have been replaced with "globalThis" upstream. That change will appear in the next 3.42.x and 3.43 releases.
> 
> As to fetch(), that comes from Emscripten-generated code. The sqlite3-node.mjs build variant blocks out that call when run from node:
> 
> ```js
>   if (!binary &&
>       typeof WebAssembly.instantiateStreaming == 'function' &&
>       !isDataURI(binaryFile) &&
>       // Avoid instantiateStreaming() on Node.js environment for now, as while
>       // Node.js v18.1.0 implements it, it does not have a full fetch()
>       // implementation yet.
>       //
>       // Reference:
>       //   https://github.com/emscripten-core/emscripten/pull/16917
>       !ENVIRONMENT_IS_NODE &&
>       typeof fetch == 'function') {
>     return fetch(binaryFile, { credentials: 'same-origin' }).then((response) => {
> ```

Ah, thanks, I see. I interpreted your comment as saying that self had already been replaced in 3.42.x/3.43.x.

If this doesn't yet work in node, perhaps we can leave this issue open?

**Comment by sgbeal** [comment]
> I interpreted your comment as saying that self had already been replaced in 3.42.x/3.43.x.

The ones in our code have all bee changed - we're "self-free" since (IIRC) that change. We have no influence over the Emscripten-generated bits, though.

> perhaps we can leave this issue open?

We don't specifically target node, and having this ticket open won't change that ;).

Nobody in the sqlite project uses node in any capacity except behind-the-scenes in the Emscripten build process, and claiming/attempting to support a platform we don't use would go poorly for us.

**Comment by kumavis** [comment]
heres what i needed to do to modify the node environment to get it to run

```ts
//
// these modificiations are used by the "@sqlite.org/sqlite-wasm" package
//

async function fetchFile(uri: string, mimeType: string = 'text/plain;charset=UTF-8'): Promise<Response> {
  if (uri.startsWith('file://')) {
    try {
      const path = new URL(uri).pathname;
      const data = await fs.promises.readFile(path);
      return new Response(data, { status: 200, statusText: 'OK', headers: { 'Content-Type': mimeType } });
    } catch (error) {
      console.error('Error reading file:', error);
      return new Response(null, { status: 404, statusText: 'File Not Found' });
    }
  }
  return new Response(null, { status: 500, statusText: 'Only file:// supported' });
}

(globalThis as any).self = globalThis;
const globalFetch = globalThis.fetch;
const wrappedFetchForSqliteWasm = async (url: string, options: RequestInit = {}): Promise<Response> => {
  if (url.endsWith('@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3.wasm')) {
    return fetchFile(url, 'application/wasm');
  }
  console.log(`fetching ${url}`);
  return globalFetch(url, options);
};
(globalThis as any).fetch = wrappedFetchForSqliteWasm;
```

**Comment by tomayac** [comment]
Did you see https://github.com/sqlite/sqlite-wasm/pull/48? Does your solution allow persisting the database?
