### ISSUE TITLE
Ability to provide URL for the WASM file

### ISSUE THREAD

**Issue by Ciantic** [tomayac/sqlite-wasm#18]
I've noticed that I would like to provide an URL to the WASM file during init. This is possible in other SQLite wrappers.

Ideally, the API I would like to have is something like this:

```js
const sqlite3 = await sqlite3InitModule({
  wasmUrl: new URL("https://example.com/sqlite.wasm")
});
```

This has one clear advantage: Ability to choose between different sqlite.wasm files, also it would future proof this with different bundlers, some of which can't handle bundling the wasm file. Issue I'm at the moment grappling with.

Thank you for considering.

P.S. Unrelated note oo1 in memory databases seems to work with Deno out of the box! Great!

**Comment by Ciantic** [comment]
Deeply sorry, I found out it works like with any other WASM thing:

```javascript
const sqlite3 = await sqlite3InitModule({
    locateFile: (file: any) => {
        return "https://cdn.jsdelivr.net/npm/@sqlite.org/sqlite-wasm@3.42.0-build2/sqlite-wasm/jswasm/sqlite3.wasm";
    },
});
```

**Comment by sgbeal** [comment]
i don't believe we can implement this because the loading part is entirely implemented by Emscripten's auto-generated code. Emscripten offers a hook for custom locations but experimentation with it in the past had proven problematic for reasons i don't recall off hand and cannot easily go look up because i'm currently limited to a phone. This feature request belongs in the main sqlite project, not this no-specific subproject, so i'm closing this ticket but will keep this request in mind for experimentation once i have a proper workstation again (hopefully by the end of July - i'm currently moving).

**Comment by sgbeal** [comment]
Okay, i stand corrected! As you say, it's not well-documented because (A) we very specifically do not document Emscripten-specific options and (B) Emscripten's own documentation of the init options is a moving target which we cannot directly support.

**Comment by Ciantic** [comment]
@sgbeal I got it already working like this:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <script type="module">
            import sqlite3InitModule from "https://cdn.jsdelivr.net/npm/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs";

            const sqlite3 = await sqlite3InitModule({
                locateFile: (file) => {
                    return "https://cdn.jsdelivr.net/npm/@sqlite.org/sqlite-wasm@3.42.0-build2/sqlite-wasm/jswasm/sqlite3.wasm";
                },
            });

            // SQLite's C API
            const capi = sqlite3.capi;
            console.log("sqlite3 version", capi.sqlite3_libversion(), capi.sqlite3_sourceid());

            // OO API example below oo1 docs https://sqlite.org/wasm/doc/tip/api-oo1.md
            const oo = sqlite3.oo1;

            const db = new oo.DB();
            db.exec(["create table t(a);", "insert into t(a) ", "values(10),(20),(30)"]);
            console.log(db);
        </script>
    </body>
</html>
```

**Comment by Ciantic** [comment]
This is something you could consider to document :) I've used emscripten a lot, that part doesn't change.

**Comment by sgbeal** [comment]
> This is something you could consider to document :) I've used emscripten a lot, that part doesn't change. 

Nope. Emscripten has pulled the rug out from under me more than once in that regard and we will not document any options other than the ones we specifically implement. Any Emscripten-specific options are "100% unsupported" (by the sqlite team) as far as we're concerned.

Additionally, we very much hope to support other build tools at some point and they will not necessarily offer the same configuration as Emscripten.

**Comment by Ciantic** [comment]
It's a good point about owning the API, but it is possible to write a wrapper for that part, make the API more official like in my original idea: 

```
const sqlite3 = await sqlite3InitModule({
  wasmUrl: new URL("https://example.com/sqlite.wasm")
});
```

Then pass internally that wasmUrl to the locateFile, and if in future you have to change from emscripten to something else, then that could be supported more nicely.

**Comment by sgbeal** [comment]
That i will definitely look into once i'm "properly" back online, but am currently moving and don't expect to be unpacked and have a workstation until the end of July at the earliest. i have noted the feature request, though, and do consider it to be sensible.

**Comment by tomayac** [comment]
(Re-opening) `Module.locateFile` is [well documented](https://emscripten.org/docs/api_reference/module.html#affecting-execution) (there’s a better deep-link, but I can’t copy it from mobile it seems). We can add a comment about this in our README. Do you want to open a quick PR?

**Comment by sgbeal** [comment]
"Well-documented" doesn't mean it won't disappear in a subsequent version ;).

Related: i updated the upstream docs to make explicit that we neither document nor directly support the Emscripten-defined config options, and that we may internally override any of them. That we have to expose that particular option-passing interface at all is unfortunate but unavoidable. Aside from that one place, we've managed to eliminate all of the Emscripten particulars from the public interface.

**Comment by tomayac** [comment]
Alright, then be it so. This gives you the option to switch from Emscripten to whatever else that may come up in the future. Those “in the know” can still use the Emscripten options as an implementation detail that may change at any time. Thanks for sharing the solution in the Issue, so it’s findable for those who search well.
