### ISSUE TITLE
Require is not defined on production build with reactjs.

### ISSUE THREAD

**Issue by umesh-gsynergy** [tomayac/sqlite-wasm#23]
Hi, I follow this article [https://developer.chrome.com/blog/sqlite-wasm-in-the-browser-backed-by-the-origin-private-file-system/](url) to implement sqlite on browser to persist data . 

I created a react app and provide the specified headers(Cross-Origin-Opener-Policy: same-origin and Cross-Origin-Embedder-Policy: require-corp) in webpack dev server. It worked as expected on localhost and created a persisted db. 

Then I build it and deployed it to the cloudflare, configure (Cross-Origin-Opener-Policy: same-origin and Cross-Origin-Embedder-Policy: require-corp) headers, I am getting an error as require is undefined .

<img width="528" alt="Screenshot 2023-07-17 at 2 30 16 PM" src="https://github.com/tomayac/sqlite-wasm/assets/67907533/3c3f27cb-c8ef-43d8-8c2a-07a3e51189da">

I research a lot but could not found how I can resolve it, any help will be appreciated

**Comment by sgbeal** [comment]
The word "require" only appears in comments and string literals in that file:

```shell
[stephan@lapdog:~/f/s/lite/ext/wasm/jswasm]$ less ^C
[stephan@lapdog:~/f/s/lite/ext/wasm/jswasm]$ grep require sqlite3-opfs-async-proxy.js
    toss("This API requires navigator.storage.getDirectory.");
     require a sync access handle but may be called without xLock()
     define its exceptions in the required level of detail.
    //metrics[op] || toss("Maintenance required: missing metrics for",op);
    //metrics[op] || toss("Maintenance required: missing metrics for",op);
        || toss("Maintenance required: this value type cannot be serialized.",v)
             is required in order for clear communication between
                toss("Maintenance required: missing state.opIds[",k,"]");
  wPost('opfs-unavailable',"Missing required OPFS APIs.");
```

There is a single scope-local variable named `require` in one other spot in the library:

```
    getDb: function(id,require=true){
      return this.dbs[id]
        || (require ? toss("Unknown (or closed) DB ID:",id) : undefined);
    }
```

i.e. this error is not originating from the canonical code. It's being introduced somewhere along the chain from the canonical source to your deployment environment.

**Comment by umesh-gsynergy** [comment]
Thankyou @sgbeal for your reply. I think webpack build has something to do with the issue. I could not opt out "@sqlite.org/sqlite-wasm" from optimisation. I switched to vite it solved the problem .
