### ISSUE TITLE
vite project example

### ISSUE THREAD

**Issue by AntonOfTheWoods** [tomayac/sqlite-wasm#25]
I might have even worse eyes than I thought, but the stackblitz project linked from the npm page that is supposed to be an example of using with vite, doesn't seem to mention vite anywhere except in a few urls. Certainly the package.json doesn't mention it. Am I missing something?

**Comment by tomayac** [comment]
Thanks for the pointer. The new example project is https://stackblitz.com/edit/vitejs-vite-ttrbwh?file=main.js. Not sure what happened, but it looks the old project picked up the contents of the repo.
