### ISSUE TITLE
Custom sqlite build

### ISSUE THREAD

**Issue by MigFerreira** [tomayac/sqlite-wasm#26]
Hey, Not an issue, more of a question.

What would be the best way to get a custom build working with this bundle?
I've built sqlite with spellfix and have it working but would like better with your wrapper.

**Comment by tomayac** [comment]
I think realistically a fork would be the best option. Unless @sgbeal has a better idea?!

**Comment by sgbeal** [comment]
The canonical build process supports adding client-side extensions by dropping a file into the tree but it depends on GNU Make, so doesn't carry over 1-to-1 into a node-based toolchain. i'm an absolutely zero when it comes to node-based tools so can't make any interesting recommendations.

**Comment by tomayac** [comment]
Let's close this for now, with the current recommendation being to fork. If you come back with a better solution, feel free to comment again, and we can see if there's a way to incorporate it.
