### ISSUE TITLE
Please update the Chrome Developers Blog and Glitch Demo

### ISSUE THREAD

**Issue by chrisamador** [tomayac/sqlite-wasm#30]
I found this project from the [Chrome Developers Blog](https://developer.chrome.com/blog/sqlite-wasm-in-the-browser-backed-by-the-origin-private-file-system/) and followed the code example in the blog post. After setting everything up, I ran into the following error: `TypeError: sqlite3.opfs.OpfsDb is not a constructor`.  After spending a good amount of time reading the source code I realized there was a change. The `OpfsDb` constructor was moved from the `opfs.OpfsDb` to the `oo1.OpfsDb`.  Since `opfs` and `oo1` are so similar it was hard to spot the change. 

Please update this line in the demos.
<img width="782" alt="image" src="https://github.com/tomayac/sqlite-wasm/assets/5768458/80e46ecf-d202-432b-b534-01896fcb6fbf">

Thanks for all the hard work on this project!

**Comment by sgbeal** [comment]
For future reference, the sqlite3.opfs object is very specifically not part of the public API. It holds only undocumented internal utilities with volatile interfaces and lifetimes.

**Comment by tomayac** [comment]
Fixed via https://github.com/GoogleChrome/developer.chrome.com/pull/7097.
