### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by fabiospampinato** [tomayac/sqlite-wasm#32]
There seems to be a origin-private file-system [ponyfill](https://github.com/jimmywarting/native-file-system-adapter) for Node, it'd be cool if it could be used to make this module isomorphic and work everywhere with good performance, with the same APIs, and without ever touching native node modules.

I'm not sure if this would require changes in this package to work.

I'm not familiar with the internals of this package, if anybody has any pointers on how to get it to work with the ponyfill I could give it shot.

**Comment by sgbeal** [comment]
ponyfill seems to provide a File System Access polyfill, not an OPFS polyfill. Those are different APIs with similar, but not not identical, goals and APIs.

**Comment by fabiospampinato** [comment]
Do you know which specific required APIs are not ponyfilled by that module?

**Comment by sgbeal** [comment]
No idea - i only browsed their docs, which specifically do not polyfill the OPFS API. The File System Access API is not supported by the core library and won't be until/unless it becomes a standard (or looks like it will imminently become one, as we expect to happen with OPFS).

**Comment by fabiospampinato** [comment]
Already, closing then.

**Comment by tomayac** [comment]
Not sure if feasible at all or not for getting this library run on Node, but the ponyfill _does_ support simulating the OPFS with various back ends, like Node: https://github.com/jimmywarting/native-file-system-adapter#file-system-sandbox.
