### ISSUE TITLE
Is there a way to manually close the OPFS handle?

### ISSUE THREAD

**Issue by terry-fei** [tomayac/sqlite-wasm#34]
since #33 can not be resolved, i want close OPFS handle manually, but when i call

```js
const db = new sqlite.oo1.OpfsDb("/main.db")
db.close()
```

it seems not close the OPFS handle, and page still hang to 3s

**Comment by sgbeal** [comment]
close() immediately asks OPFS to release the handle, but the bowser can then take as long as it wants to actually do it, especially in browsers released before March, when close() was still async. Chrome made that change earlier - i don't recall exactly when.

**Comment by terry-fei** [comment]
but, after i call `db.close()`, wait some seconds or minutes, then refresh page, it still hang for 3s, seems not close OPFS file handle

**Comment by terry-fei** [comment]
https://github.com/tomayac/sqlite-wasm/assets/4183342/43856fd2-95f8-4bc1-ae85-36da1c7eecb4

**Comment by sgbeal** [comment]
What does your Network tab tell you during that time? Is some resource perhaps choking?

It's not clear by your report whether the init time includes loading the OPFS DB. If it does, please try timing just the db-open part.

**Comment by terry-fei** [comment]
I have finally figured out that the issue is caused by using `db.prepare` to create a `statement` but not calling `finalize`. This seems to be the reason why the OPFS handle is not released when refreshing the page. If I don't call finalize, will the statement be garbage collected? I need to reuse the statement for better performance.

**Comment by sgbeal** [comment]
Excellent :). Garbage collection never applies to C-side resources. Their JS-side parts can get GC'd but that doesn't affect C. Any sqlite resources created via JS have to be explicitly finalized/closed from JS.

**Comment by terry-fei** [comment]
Thank you for your help!
