### ISSUE TITLE
Is it possible to open a SQLite3 file selected from the file picker?

### ISSUE THREAD

**Issue by c-bata** [tomayac/sqlite-wasm#5]
Hello, thank you for creating this library. It looks very interesting to me.

I have a question about how to open a SQLite3 file selected from the file picker.
Unlike the sqlite-wasm example, I'm trying to import the data from a SQLite3 file which is selected from the user via the [window.showOpenFilePicker()](https://developer.mozilla.org/en-US/docs/Web/API/window/showOpenFilePicker)  method or something. Do you have any useful examples, resources, or advice?

**Comment by sgbeal** [comment]
The library itself has no components for working with user interaction or HTML/DOM elements. We do have an example of uploading a db using file picker, though: <https://sqlite.org/wasm/doc/trunk/cookbook.md>
