### ISSUE TITLE
Virtual Tabs not working

### ISSUE THREAD

**Issue by hubgit2345** [tomayac/sqlite-wasm#9]
Calling `sqlite3.vtab.setupModule(config)`  I get:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'StructType')`
`    at callee (sqlite3-bundler-friendly.mjs:11854:53)`
`    at installMethods (sqlite3-bundler-friendly.mjs:11944:15)`
`    at vtab.setupModule (sqlite3-bundler-friendly.mjs:12156:15)`

If I comment out these, the error does not happen.

`          // if (!(tgt instanceof sqlite3.StructBinder.StructType)) {`
`          //   toss('Usage error: target object is-not-a StructType.');`
`          // } else if (!(func instanceof Function) && !wasm.isPtr(func)) {`
`          //   toss('Usage errror: expecting a Function or WASM pointer to one.');`
`          // }`

I don't know of the proper way to fix it, but seems the code expects some time of context it is not receiving? Thank you.

**Comment by sgbeal** [comment]
Please report such problems at sqlite.org/forum and always include the version number. To the best of my recollection this problem was solved several months ago.

**Comment by hubgit2345** [comment]
No problem. Thank you. I thought maybe this was npm-specific but maybe not.
